kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-boot-vms
spec:
  selector:
    matchLabels:
      app: spring-boot-vms
      version: v01
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-boot-vms
        version: v01
    spec:
      containers:
      - name: spring-boot-vms
        image: vms-docker:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80